[package]
name = "rustracer"
version = "0.1.0"
authors = ["Boris Stoyanov <bstoyanov@coursera.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[net]
git-fetch-with-cli = true
